// <auto-generated />
namespace Tekconf.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-beta1-40122")]
    public sealed partial class SpeakerWebsite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpeakerWebsite));
        
        string IMigrationMetadata.Id
        {
            get { return "201602031527382_SpeakerWebsite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
