// <auto-generated />
namespace Tekconf.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-beta1-40122")]
    public sealed partial class LatLongPrecision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LatLongPrecision));
        
        string IMigrationMetadata.Id
        {
            get { return "201601172153117_LatLongPrecision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
